---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-nginx
  namespace: flux-system
spec:
  interval: 1m
  path: "./nortura-infra/nginx-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-prometheus
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  path: "./nortura-infra/monitoring/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-monitoring-extras
  namespace: flux-system
spec:
  interval: 1m
  path: "./nortura-infra/monitoring/extras"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: dev-prometheus

---
# NEW: ingress controller
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-ingress
  namespace: flux-system
spec:
  interval: 1m
  path: "./nortura-infra/ingress"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true

